sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t asfandyar9/docker-react -f Dockerfile.dev .

script:
  - docker run asfandyar9/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-12938934"
  bucket_path: "docker"
  on:
    branch: master
